<?php

namespace App\Helpers;

class Constants
{
    const STATUS_DELIVERY_PENDENTE = 1;
    const STATUS_DELIVERY_EM_TRANSITO = 2;
    const STATUS_DELIVERY_ENTREGUE = 3;
    const STATUS_DELIVERY_CANCELADA = 4;
    const STATUS_DELIVERY_DOCUMENTO_PERDIDO = 5;
    const STATUS_DELIVERY_DOCUMENTO_DANIFICADO = 6;
    const STATUS_DELIVERY_TENTAR_DENOVO = 7;
    const STATUS_DELIVERY_ENTREGA_RECUSADA = 8;
}
